# Generated by Django 5.2 on 2025-04-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_data',
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
